version: '3.8'
services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb_container
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: aujudo
    volumes:
      - ./arangodb_data:/var/lib/arangodb3       # Maps to a local folder
      - ./arangodb_app:/var/lib/arangodb3-apps   # Maps to a local folder
    networks:
      - arangodb_network

volumes:
  arangodb_data:
  arangodb_app:

networks:
  arangodb_network:
    driver: bridge

